### ISSUE TITLE
main.xml: us.costan.chrome.ChromeView

### ISSUE THREAD

**Issue by yoyeung** [thedracle/cordova-android-chromeview#10]
java.lang.ClassNotFoundException: us.costan.chrome.ChromeView
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)

**Comment by thedracle** [comment]
ChromeView is not included in this project, please follow the build instructions for it, and include it in your project:

https://github.com/thedracle/cordova-android-chromeview/issues/1

**Comment by yoyeung** [comment]
i included the .jar file into the libs folder. I am using Eclipse to build the project.
When open main.xml in eclipse, i will have this error message for me.

I have no idea. I change the java version from 1.7 to 1.6 and update the android sdk.
There are no any changes.

![error](https://f.cloud.github.com/assets/451538/1470468/f350a012-45bb-11e3-981c-73cbe20c61c1.jpg)
![screen2](https://f.cloud.github.com/assets/451538/1470469/f3779898-45bb-11e3-8e5f-45749bcf1228.PNG)

**Comment by thedracle** [comment]
Have you called ChromeView's initialize in your Application class's onCreate?

See: https://github.com/pwnall/chromeview
Initialize Chromium

import us.costan.chrome.ChromeView;
import android.app.Application;

public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        ChromeView.initialize(this);
    }
}
Now you can use ChromeView in the same contexts as you would use WebView.

**Comment by yoyeung** [comment]
Great!!! I create a new project to setup your chromeview. It's fine.
I found out this error when i using the test project which include in the project .
I think there have some setting issue in this project.
By the way thanks for your help.

**Comment by ariselseng** [comment]
@yoyeung 
Hi, could you upload your final code for us others to try it out? I have yet to get it working :/

**Comment by yoyeung** [comment]
@cowai 
i am working on work with chromeview directly.
But i will try to create a project to directly work with cordova-android-chromeview
Can you show us what error message you got?

**Comment by josedefreitasc** [comment]
Hi @yoyeung and @cowai, I will appreciate the help guys, I try to make this work and i can't, here I write all the steps that I make and the error message, [here](https://github.com/thedracle/cordova-android-chromeview/issues/4#issuecomment-27821392)
If I or we make this work, I will leave tutorial

**Comment by yoyeung** [comment]
@josedefreitasc, i have follow your step to work on project but i got  a different issue.
I want to find the stable version and work on it. Unlucky i cannot find it.
I am using 10.9, android update sdk with ndk.

**Comment by vipulanurag** [comment]
Hi,

I am getting the below image error while importing chromview:

![error](https://cloud.githubusercontent.com/assets/715103/3879529/a714edf8-2179-11e4-938f-9aeac666675e.png)

I followed the steps but still. I am unable to rectify this one...
