### ISSUE TITLE
Application crash in android emulator

### ISSUE THREAD

**Issue by gen-failure** [thedracle/cordova-android-chromeview#2]
Hi,

I tried to compile one of my existing PG applications and I found this error aftr launch

I/ActivityManager(  302): Start proc org.darkencz.test.wgl for activity org.darkencz.test.wgl/.WGLTest: pid=988 uid=10046 gids={50046, 1006, 3003, 1015, 1028}
E/Trace   (  988): error opening trace file: No such file or directory (2)
I/CordovaLog(  988): Changing log level to DEBUG(3)
D/CordovaActivity(  988): CordovaActivity.onCreate()
W/dalvikvm(  988): No implementation found for native Lorg/chromium/android_webview/AwContents;.nativeInit:(Lorg/chromium/android_webview/AwWebContentsDelegate;Lorg/chromium/android_webview/AwContentsClientBridge;)I
D/AndroidRuntime(  988): Shutting down VM
W/dalvikvm(  988): threadid=1: thread exiting with uncaught exception (group=0x40a71930)
E/AndroidRuntime(  988): FATAL EXCEPTION: main
E/AndroidRuntime(  988): java.lang.UnsatisfiedLinkError: Native method not found: org.chromium.android_webview.AwContents.nativeInit:(Lorg/chromium/android_webview/AwWebContentsDelegate;Lorg/chromium/android_webview/AwContentsClientBridge;)I
E/AndroidRuntime(  988):    at org.chromium.android_webview.AwContents.nativeInit(Native Method)
E/AndroidRuntime(  988):    at org.chromium.android_webview.AwContents.<init>(AwContents.java:363)
E/AndroidRuntime(  988):    at org.chromium.android_webview.AwContents.<init>(AwContents.java:322)
E/AndroidRuntime(  988):    at us.costan.chrome.ChromeView.<init>(ChromeView.java:90)
E/AndroidRuntime(  988):    at us.costan.chrome.ChromeView.<init>(ChromeView.java:62)
E/AndroidRuntime(  988):    at org.apache.cordova.CordovaWebView.<init>(CordovaWebView.java:130)
E/AndroidRuntime(  988):    at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:327)
E/AndroidRuntime(  988):    at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:390)
E/AndroidRuntime(  988):    at org.darkencz.test.wgl.WGLTest.onCreate(WGLTest.java:32)
E/AndroidRuntime(  988):    at android.app.Activity.performCreate(Activity.java:5104)
E/AndroidRuntime(  988):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
E/AndroidRuntime(  988):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
E/AndroidRuntime(  988):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
E/AndroidRuntime(  988):    at android.app.ActivityThread.access$600(ActivityThread.java:141)
E/AndroidRuntime(  988):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
E/AndroidRuntime(  988):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(  988):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(  988):    at android.app.ActivityThread.main(ActivityThread.java:5041)
E/AndroidRuntime(  988):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  988):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(  988):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime(  988):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime(  988):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  302):   Force finishing activity org.darkencz.test.wgl/.WGLTest
D/dalvikvm(  302): GC_FOR_ALLOC freed 241K, 61% free 5089K/12988K, paused 66ms, total 71ms
D/dalvikvm(  302): GC_FOR_ALLOC freed 42K, 59% free 5345K/12988K, paused 62ms, total 64ms
W/ActivityManager(  302): Activity pause timeout for ActivityRecord{410feb90 u0 org.darkencz.test.wgl/.WGLTest}

**Comment by thedracle** [comment]
You still need to reference the ChromeView project, create an Application class for your application, insert it into your AndroidManifest.xml, and inside of 'onCreate' call 'ChromeView.initialize(this)' in order to get ChromeView to load its native dependencies.

See the ChromeView description for how this works:
https://github.com/pwnall/chromeview

Under the 'Initialize Chromium' section.

Sorry for the sparse documentation on the extra process, and not bundling in Chromium. It's far too large to be part of the active repository.
